// AWS Cognito and API Configuration
// Auto-generated by update-config.sh on Thu Mar  5 12:53:59 EST 2026

const CONFIG = {
    // API Gateway endpoint
    apiEndpoint: 'https://ms0hk6rhol.execute-api.us-east-1.amazonaws.com',

    // Cognito User Pool Configuration
    cognito: {
        userPoolId: 'us-east-1_Xzm1CCwb3',
        userPoolRegion: 'us-east-1',
        appClientId: '6n4p327ohinulk7g8g6nr66hgv',
        domain: 'lantern-lounge-calendar-production.auth.us-east-1.amazoncognito.com'
    },

    // API Routes
    api: {
        getItems: '/calendar/items',
        createItem: '/calendar/items',
        updateItem: '/calendar/items',
        deleteItem: '/calendar/items'
    }
};

// Export for use in calendar.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
