#!/bin/bash

# Script to automatically update config.js with values from OpenTofu outputs
# Usage: ./update-config.sh

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INFRA_DIR="$SCRIPT_DIR/../../infrastructure/aws"
CONFIG_FILE="$SCRIPT_DIR/config.js"

echo "🔧 Updating calendar configuration from OpenTofu outputs..."

# Check if infrastructure directory exists
if [ ! -d "$INFRA_DIR" ]; then
    echo "❌ Error: Infrastructure directory not found at $INFRA_DIR"
    exit 1
fi

# Navigate to infrastructure directory
cd "$INFRA_DIR"

# Check if OpenTofu is initialized
if [ ! -d ".terraform" ]; then
    echo "❌ Error: OpenTofu not initialized. Run 'tofu init' first."
    exit 1
fi

# Get outputs from OpenTofu
echo "📊 Fetching OpenTofu outputs..."

API_ENDPOINT=$(tofu output -raw api_gateway_endpoint 2>/dev/null || echo "")
USER_POOL_ID=$(tofu output -raw cognito_user_pool_id 2>/dev/null || echo "")
APP_CLIENT_ID=$(tofu output -raw cognito_app_client_id 2>/dev/null || echo "")
COGNITO_DOMAIN=$(tofu output -raw cognito_domain 2>/dev/null || echo "")
AWS_REGION=$(tofu output -raw -json frontend_config 2>/dev/null | jq -r '.userPoolRegion' || echo "us-east-1")

# Validate outputs
if [ -z "$API_ENDPOINT" ] || [ -z "$USER_POOL_ID" ] || [ -z "$APP_CLIENT_ID" ] || [ -z "$COGNITO_DOMAIN" ]; then
    echo "❌ Error: Failed to retrieve all required outputs from OpenTofu"
    echo "   Make sure you've run 'tofu apply' successfully"
    exit 1
fi

# Create the config.js file
cat > "$CONFIG_FILE" << EOF
// AWS Cognito and API Configuration
// Auto-generated by update-config.sh on $(date)

const CONFIG = {
    // API Gateway endpoint
    apiEndpoint: '$API_ENDPOINT',

    // Cognito User Pool Configuration
    cognito: {
        userPoolId: '$USER_POOL_ID',
        userPoolRegion: '$AWS_REGION',
        appClientId: '$APP_CLIENT_ID',
        domain: '$COGNITO_DOMAIN.auth.$AWS_REGION.amazoncognito.com'
    },

    // API Routes
    api: {
        getItems: '/calendar/items',
        createItem: '/calendar/items',
        updateItem: '/calendar/items',
        deleteItem: '/calendar/items'
    }
};

// Export for use in calendar.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
EOF

echo "✅ Configuration updated successfully!"
echo ""
echo "📋 Configuration values:"
echo "   API Endpoint:    $API_ENDPOINT"
echo "   User Pool ID:    $USER_POOL_ID"
echo "   App Client ID:   $APP_CLIENT_ID"
echo "   Cognito Domain:  $COGNITO_DOMAIN.auth.$AWS_REGION.amazoncognito.com"
echo ""
echo "🚀 Next step: Upload files to S3"
echo "   Run: aws s3 sync $SCRIPT_DIR s3://www.lanternlounge.org/ --exclude '.DS_Store' --exclude '*.md' --exclude '*.sh'"
