#!/usr/bin/env node
/**
 * Generates src/config/aws-config.js from OpenTofu outputs.
 * Run via: node scripts/generate-config.js
 * Or:      make generate-config
 */

import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, '../../..');

function tfOutput(moduleDir, outputName) {
  const cwd = path.join(ROOT, moduleDir);
  try {
    return execSync(`tofu output -raw ${outputName}`, { cwd, stdio: ['pipe', 'pipe', 'pipe'] })
      .toString()
      .trim();
  } catch (e) {
    console.error(`❌ Failed to read output "${outputName}" from ${moduleDir}`);
    console.error(`   Make sure the module is deployed: cd ${moduleDir} && tofu apply`);
    process.exit(1);
  }
}

console.log('Reading OpenTofu outputs...');

const apiEndpoint        = tfOutput('app/calendar',  'api_gateway_endpoint');
const checkinsApiEndpoint = tfOutput('app/check-ins', 'api_gateway_endpoint');
const usersApiEndpoint   = tfOutput('app/cognito',   'users_api_endpoint');
const userPoolId         = tfOutput('app/cognito',   'cognito_user_pool_id');
const appClientId        = tfOutput('app/cognito',   'cognito_user_pool_client_id');
const cognitoDomain      = tfOutput('app/cognito',   'cognito_domain');

const content = `// AWS Cognito and API Configuration
// Auto-generated by scripts/generate-config.js — do not edit manually

const CONFIG = {
  // API Gateway endpoints
  apiEndpoint: import.meta.env.VITE_API_ENDPOINT ?? '${apiEndpoint}',
  checkinsApiEndpoint: import.meta.env.VITE_CHECKINS_API_ENDPOINT ?? '${checkinsApiEndpoint}',
  usersApiEndpoint: import.meta.env.VITE_USERS_API_ENDPOINT ?? '${usersApiEndpoint}',

  // Cognito User Pool Configuration
  cognito: {
    userPoolId: '${userPoolId}',
    userPoolRegion: 'us-east-1',
    appClientId: '${appClientId}',
    domain: '${cognitoDomain}.auth.us-east-1.amazoncognito.com'
  },

  // API Routes
  api: {
    getItems: '/calendar/items',
    createItem: '/calendar/items',
    updateItem: '/calendar/items',
    deleteItem: '/calendar/items',
    getPass: '/wallet/pass',
    getApplePass: '/wallet/apple',
    checkIn: '/checkin',
    checkInScan: '/checkin/scan'
  }
};

export default CONFIG;
`;

const outputPath = path.resolve(__dirname, '../src/config/aws-config.js');
fs.writeFileSync(outputPath, content);
console.log('✅ Generated src/config/aws-config.js');
