# Private key generated by Tofu — never leaves AWS after first apply
resource "aws_ssm_parameter" "private_key" {
  name  = "/lantern-lounge/apple/wallet-private-key"
  type  = "SecureString"
  value = tls_private_key.pass_signing.private_key_pem
}

resource "aws_ssm_parameter" "pass_type_id" {
  name  = "/lantern-lounge/apple/wallet-pass-type-id"
  type  = "String"
  value = var.pass_type_id
}

resource "aws_ssm_parameter" "team_id" {
  name  = "/lantern-lounge/apple/wallet-team-id"
  type  = "String"
  value = var.team_id
}

# Apple-issued certificate — only created after the user has it (phase 2)
resource "aws_ssm_parameter" "certificate_pem" {
  count = var.certificate_pem != "" ? 1 : 0

  name  = "/lantern-lounge/apple/wallet-certificate-pem"
  type  = "SecureString"
  value = var.certificate_pem
}
